### ISSUE TITLE
Issues with saving/playback of videos

### ISSUE THREAD

**Issue by aidifla** [analogdevicesinc/aditof_sdk#55]
1.	The filename box will only allow a few letters to be entered.  I can only use the letters e, d, f, a.  I am unclear why I can’t use all of the characters on my keyboard.
2.	We can’t add an extension or file type to the name of the video file.  It plays back on the ADI software, but we would like to export to another video file, share with colleagues.
3.	We would like to pull depth data from the frames.  At this point we can only look at the images and see false color.  We would like to be able to pull frame data out of the video files and view depth data to compare with our test set up.  Do the video files provide depth information, or just intensity, color information?

**Comment by DanielGuramulta** [comment]
1. The problem there is that the library we are using for graphical user interface has no "line edit" and we added a fake one that captures keys (0-9 and A-F) in order to write registers. We used this one for the filename.
2. Adding an extension won't change anything about the file. The only way it can be saved is in binary format. The file starts with a header which contains information on how the data will be read from it. The header has height, width, fps information followed by frame data.
3. The frames saved in the file contain depth and ir information. The color is provided when displaying this frames by the demo.
