### ISSUE TITLE
where can get 96TOF functions documents in python

### ISSUE THREAD

**Issue by SumingNTUT** [analogdevicesinc/aditof_sdk#563]
Hi 
If I want to set camera status to idle, close or when I trigger camera that grab IR or depth map
How can I do ?

thanks

**Comment by dNechita** [comment]
Hi,
You want to stop the camera from streaming? And then start it again? And so on?

**Comment by SumingNTUT** [comment]
Yes, I want set "stop" or "start" to camera, and does camera have trigger model from software or hardware?

**Comment by SumingNTUT** [comment]
> Hi,
> You want to stop the camera from streaming? And then start it again? And so on?
Yes, I want set "stop" or "start" to camera, and does camera have trigger model from software or hardware?

**Comment by SumingNTUT** [comment]
> Hi,
> You want to stop the camera from streaming? And then start it again? And so on?

Yes, I want set "stop" or "start" to camera, and does camera have trigger model from software or hardware?

**Comment by dNechita** [comment]
Hi,

Currently, we don't have documentation for the Python API. All available functions and types can be found here: https://github.com/analogdevicesinc/aditof_sdk/blob/master/bindings/python/aditofpython.cpp
You can take a look at some of our examples to see how the Python calls are being made: https://github.com/analogdevicesinc/aditof_sdk/blob/master/bindings/python/examples/

The start and stop don't work for this camera due to a driver limitation. The camera will start streaming when calling the setFrameType() method of the Camera class. And it will stop streaming once the Camera instance is destroyed.

The camera trigger is hardware.

**Comment by SumingNTUT** [comment]
> hardware
