### ISSUE TITLE
Not able to achieve 30 fps in Dragonboard410c with Latest SDK 

### ISSUE THREAD

**Issue by Radhika-Sekar** [analogdevicesinc/aditof_sdk#59]
I have followed up the https://github.com/analogdevicesinc/aditof_sdk/issues/16 issue and it says latest SDK can output 30 fps in Dragonboard410c.

I have built and tested latest SDK integrated with changes as mentioned in https://github.com/analogdevicesinc/aditof_sdk/issues/16 issue on Dragonboard410c,But it doesn't result 30 fps. Now SDK output stream achieved is only 14 fps.

Can someone please confirm is it possible to get 30 fps streaming with latest SDK ? or As mentioned in https://github.com/analogdevicesinc/aditof_sdk/blob/master/doc/dragonboard410c/user_guide.md page , application processes the frame at lower rate because of system load ?

**Comment by dNechita** [comment]
Hi,

The SDK can capture frames at 30 fps. Any additional processing can decrease the fps. For instance the aditof-demo is an example application that uses the SDK but in addition to capturing the frames it does other operations on the frames in order to display them with OpenCV. These operations increase the system load and cause a drop in the fps.
