### ISSUE TITLE
Help building and running python bindings

### ISSUE THREAD

**Issue by bitslip6** [analogdevicesinc/aditof_sdk#72]
I was able to compile aditofpython.cpp by creating this setup.py:
I have copied the aditof header and compiled library code into /usr/include and /usr/lib respectively. 

after calling "python setup.py install" I get these 2 files:
`ls -l /usr/local/lib/python2.7/dist-packages/aditofpython*
-rw-r--r-- 1 root staff     212 Aug 27 23:43 /usr/local/lib/python2.7/dist-packages/aditofpython-1.0.egg-info
-rwxr-xr-x 1 root staff 4751956 Aug 27 23:43 /usr/local/lib/python2.7/dist-packages/aditofpython.so`

running the first_frame.py gives me:
```
sudo python2.7 first_frame.py 
Traceback (most recent call last):
  File "first_frame.py", line 1, in <module>
    import aditofpython as tof
ImportError: /usr/lib/libaditof.so.1.0: undefined symbol: _ZN6aditof5Utils21buildCalibrationCacheEffs
```

here is . my setup.py: 
any suggestions?

```
#!/usr/bin/python
from distutils.core import setup, Extension

module1 = Extension('aditofpython',
                    define_macros = [('MAJOR_VERSION', '1'),
                                     ('MINOR_VERSION', '0')],
                    include_dirs = ['/usr/include'],
                    libraries = ['aditof'],
                    library_dirs = ['/usr/lib'],
                    sources = ['aditofpython.cpp'])

setup (name = 'aditofpython',
       version = '1.0',
       description = 'ADI TOF Package',
       ext_modules = [module1])
```

Any help would be greatly appreciated!

**Comment by DanielGuramulta** [comment]
Hello.

I tried to reproduce the issue but everything worked fine. `setup.py` looks good. Here are the steps that I tried in order to reproduce the problem:
1) I made sure to have a clean build of the sdk (the step for building the sdk can be found here: https://github.com/analogdevicesinc/aditof_sdk/blob/master/doc/linux/user_guide.md#building-the-sdk)
2) Once the build is done in the build directory I ran this two commands to get the libraries and include folder in `/usr`:

- `sudo cp sdk/libaditof.so* /usr/lib/`

- `sudo cp -r ../sdk/include/aditof/ /usr/include/`
3) In the python bindings folder I ran `sudo python setup.py install`
4) To run the python example I ran `python2.7 first_frame.py`

Could you try again with a clean build of the sdk? Also make sure to delete the old libraries and include directory from `/usr` before copying the new files after the build.
